module.exports = [
    {
        name: "New York",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "4.8%",
        ingredient_1: "New York",
        ingredient_2: "New York",
        ingredient_3: "New York",
        ingredient_4: "New York",
        ingredient_5: "New York",
        ingredient_6: "New York",
        ingredient_7: "New York",
        description: 8405837
    },
    {
        name: "Los Angeles",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "4.8%",
        ingredient_1: "California",
        ingredient_2: "California",
        ingredient_3: "California",
        ingredient_4: "California",
        ingredient_5: "California",
        ingredient_6: "California",
        ingredient_7: "California",
        description: 3884307
    },
    {
        name: "Chicago",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "-6.1%",
        ingredient_1: "Illinois",
        ingredient_2: "Illinois",
        ingredient_3: "Illinois",
        ingredient_4: "Illinois",
        ingredient_5: "Illinois",
        ingredient_6: "Illinois",
        ingredient_7: "Illinois",
        description: 2718782
    },
    {
        name: "Houston",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "11.0%",
        ingredient_1: "Texas",
        ingredient_2: "Texas",
        ingredient_3: "Texas",
        ingredient_4: "Texas",
        ingredient_5: "Texas",
        ingredient_6: "Texas",
        ingredient_7: "Texas",
        description: 2195914
    },
    {
        name: "Philadelphia",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "2.6%",
        ingredient_1: "Pennsylvania",
        ingredient_2: "Pennsylvania",
        ingredient_3: "Pennsylvania",
        ingredient_4: "Pennsylvania",
        ingredient_5: "Pennsylvania",
        ingredient_6: "Pennsylvania",
        ingredient_7: "Pennsylvania",
        description: 1553165
    },
    {
        name: "Phoenix",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "14.0%",
        ingredient_1: "Arizona",
        ingredient_2: "Arizona",
        ingredient_3: "Arizona",
        ingredient_4: "Arizona",
        ingredient_5: "Arizona",
        ingredient_6: "Arizona",
        ingredient_7: "Arizona",
        description: 1513367
    },
    {
        name: "San Antonio",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "21.0%",
        ingredient_1: "Texas",
        ingredient_2: "Texas",
        ingredient_3: "Texas",
        ingredient_4: "Texas",
        ingredient_5: "Texas",
        ingredient_6: "Texas",
        ingredient_7: "Texas",
        description: 1409019
    },
    {
        name: "San Diego",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "10.5%",
        ingredient_1: "California",
        ingredient_2: "California",
        ingredient_3: "California",
        ingredient_4: "California",
        ingredient_5: "California",
        ingredient_6: "California",
        ingredient_7: "California",
        description: 1355896
    },
    {
        name: "Dallas",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "5.6%",
        ingredient_1: "Texas",
        ingredient_2: "Texas",
        ingredient_3: "Texas",
        ingredient_4: "Texas",
        ingredient_5: "Texas",
        ingredient_6: "Texas",
        ingredient_7: "Texas",
        description: 1257676
    },
    {
        name: "San Jose",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "10.5%",
        ingredient_1: "California",
        ingredient_2: "California",
        ingredient_3: "California",
        ingredient_4: "California",
        ingredient_5: "California",
        ingredient_6: "California",
        ingredient_7: "California",
        description: 998537
    },
    {
        name: "Austin",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "31.7%",
        ingredient_1: "Texas",
        ingredient_2: "Texas",
        ingredient_3: "Texas",
        ingredient_4: "Texas",
        ingredient_5: "Texas",
        ingredient_6: "Texas",
        ingredient_7: "Texas",
        description: 885400
    },
    {
        name: "Indianapolis",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "7.8%",
        ingredient_1: "Indiana",
        ingredient_2: "Indiana",
        ingredient_3: "Indiana",
        ingredient_4: "Indiana",
        ingredient_5: "Indiana",
        ingredient_6: "Indiana",
        ingredient_7: "Indiana",
        description: 843393
    },
    {
        name: "Jacksonville",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "14.3%",
        ingredient_1: "Florida",
        ingredient_2: "Florida",
        ingredient_3: "Florida",
        ingredient_4: "Florida",
        ingredient_5: "Florida",
        ingredient_6: "Florida",
        ingredient_7: "Florida",
        description: 842583
    },
    {
        name: "San Francisco",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "7.7%",
        ingredient_1: "California",
        ingredient_2: "California",
        ingredient_3: "California",
        ingredient_4: "California",
        ingredient_5: "California",
        ingredient_6: "California",
        ingredient_7: "California",
        description: 837442
    },
    {
        name: "Columbus",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-XkySihon_1vO738aeah1NEASxQ07vLTee1P6cJ_MlVfaokghr5OoJH02Er3-DIa3Nck&usqp=CAU",
        formula: "14.8%",
        ingredient_1: "Ohio",
        ingredient_2: "Ohio",
        ingredient_3: "Ohio",
        ingredient_4: "Ohio",
        ingredient_5: "Ohio",
        ingredient_6: "Ohio",
        ingredient_7: "Ohio",
        description: 822553
    }
]