module.exports = [
    {
        name: "Beetroot Halwa Recipe",
        time: "35min",
        image: "https://c.ndtvimg.com/2023-11/rt2d5vdg_beetroot-halwa_625x300_10_November_23.jpg",
        method: "In a wide pan, heat 2 tsp of ghee.2.Add the skin peel to the pan and sauté for a few minutes.3.Pour in the milk and cook over low to medium flame for about 15 minutes until the vegetables are thoroughly cooked and soft.4.Once the vegetables are cooked, add sugar and mava to the pan.5.Continue cooking for an additional 5 minutes until the mixture achieves a thick consistency.6.In a separate pan, sauté the assorted nuts in ghee until they turn a golden colour.7.Add the remaining ghee, cardamom pods and seeds, as well as the sautéed nuts, to the main mixture.8.Mix all the ingredients th,oroughly.9.Serve and enjoy the dish while it is warm.",
        ingredients:["potato", "oil", "flour", "curd"],
        description: "This beetroot halwa is a winter delight. If you want, you can easily make this Indian dessert at home this Diwali",
    },
    {
        name: "Green Moong Cutlet Recipe",
        time: "30min",
        image: "https://c.ndtvimg.com/2023-07/s1ap2vmo_cutlet_625x300_30_July_23.jpg",
        method: "1.Soak the green moong dal (mung beans) overnight or for 5-6 hours. Drain the water and coarsely grind the moong to form a thick paste.2.Wash the poha once under running water and drain. Keep aside.3.Roast the besan on low flame until it turns light brown and emits aroma.4.In a large bowl, mix the green moong paste, poha, besan, onion, chillies, ginger and coriander.5.Next, add the masala powders mentioned above. Combine all the ingredients we,ll. Taste to adjust salt.6.Form circular shapes (like patties or tikkis) of the mixture and pan-fry them on both sides on medium flame. Serve the cutlets hot with green chutney and/ or ketchup.",
        ingredients:["potato", "milk", "sugar", "ginger"],
        description: " This delicious cutlet is packed with the goodness of green moong (mung beans), onions, poha and spices. Healthy and flavourful, this high-protein moong cutlet can be enjoyed even while dieting. You can choose to pan-fry, air-fry or bake it, according to your preference.",
    },
    {
        name: "No-Oil Vegetable Pulao Recipe",
        time: "25min",
        image: "https://c.ndtvimg.com/2023-01/bcdjpkg_pulao_625x300_31_January_23.jpg",
        method: "1.First, wash the rice nicely and soak it in water for around 20-30 minutes. Add half of the milk to the pressure cooker and allow it to heat.2.Now, add cloves, bay leaves, nutmeg, elaichi, and the cinnamon stick. Allow it to come to a boil.3.Next, add the chopped carrots, cauliflower, and beans. Then, we need to season it with haldi, salt, and sugar. You could also add some cashew nuts at this stage for extra flavour.4.Next, add the soaked rice and saute it in the cooker. Once the milk dries up, add the remaining milk and some water.5.Cover the lid of the cooker and cook the vegetable pulao for one whistle.",
        ingredients:["milk", "sugar", "flour", "oil"],
        description: "Pulao is such a delicious recipe that we can make in few minutes. But today we are bring an amazing recipe of pulao which can be made without oil and it can be good option for those people who are weight watchers.",
    },
    {
        name: "Masoor Dal Khichdi Recipe",
        time: "30min",
        image: "https://c.ndtvimg.com/2023-03/m4rcpuv8_gajar-khichdi_625x300_04_March_23.jpg",
        method: "1.First, rinse the masoor dal and rice separately under running water until the water runs clear. Soak them in water for around 30 mins.2.Now, heat some ghee in a pressure cooker. Add cumin seeds and let them splutter. Add chopped onions and saute until they turn golden brown in colour.3.Next, add ginger-garlic paste and saute for another minute or so. Add chopped tomatoes and cook until they turn soft.4.Drain the water from the soaked dal and rice and add them to the cooker.5.Add haldi, garam masala, and salt. Mix well. Now, add 4 cups of water and combine everything together.6.Cover the lid and allow it to cook on high heat for two whistles, then reduce the heat and cook for another 10 mins.",
        ingredients:["tomato", "curd", "ginger", "salt"],
        description: "Dal is staple in indian household, and masoor dal khichdi is comfort food for many of us. Masoor dal recipe is very easy to make and you can pair with roti or rice.",
    },
    {
        name: "Masoor Dal Khichdi Recipe",
        time: "30min",
        image: "https://c.ndtvimg.com/2023-03/m4rcpuv8_gajar-khichdi_625x300_04_March_23.jpg",
        method: "1.First, rinse the masoor dal and rice separately under running water until the water runs clear. Soak them in water for around 30 mins.2.Now, heat some ghee in a pressure cooker. Add cumin seeds and let them splutter. Add chopped onions and saute until they turn golden brown in colour.3.Next, add ginger-garlic paste and saute for another minute or so. Add chopped tomatoes and cook until they turn soft.4.Drain the water from the soaked dal and rice and add them to the cooker.5.Add haldi, garam masala, and salt. Mix well. Now, add 4 cups of water and combine everything together.6.Cover the lid and allow it to cook on high heat for two whistles, then reduce the heat and cook for another 10 mins.",
        ingredients:["tomato", "curd", "ginger", "salt"],
        description: "Dal is staple in indian household, and masoor dal khichdi is comfort food for many of us. Masoor dal recipe is very easy to make and you can pair with roti or rice.",
    },
    {
        name: "Lauki Besan Cheela Recipe",
        time: "25min",
        image: "https://c.ndtvimg.com/2023-11/rt2d5vdg_beetroot-halwa_625x300_10_November_23.jpg",
        method: "1.In a large bowl, mix grated lauki, besan, salt, sugar, as well as the chopped veggies and spices mentioned above. Add 1 tbsp oil and mix.2.Add a little water and combine all ingredients we,ll to make a thick batter. Note that a runny batter will not hold the heavier ingredients. T,aste to adjust salt and spice level. Let the batter rest for 5 minutes.3.In a pan/ tawa, heat a little oil or ghee to start cooking the cheela. Ladle 1-2 spoons of the batter on top and carefully spread it in a round shape on the tawa.4.Lower the heat to medium flame and allow the cheela to cook. Add more ghee/ oil around it as required.5.As the edges turn brown, flip the cheela over and cook until both sides are firm and golden brown. Serve the cheelas hot with chutney of choice.",
        ingredients:["milk", "jeera", "salt", "water"],
        description: "This wholesome besan lauki cheela is packed with irresistible flavours and the goodness of fresh veggies. Grated lauki (bottle gourd) is mixed with besan, spices, onion and tomato to make this healthy dish. Enjoy this cheela for a quick and tasty breakfast, lunch or dinner.",
    },
    {
        name: "Sri Lankan Pol Roti Recipe",
        time: "25min",
        image: "https://c.ndtvimg.com/2023-08/v9qdbrf8_naan_625x300_08_August_23.jpg",
        method: "1.To make this roti, add grated coconut, green chillies, onion, curry leaves, and salt to a bowl. Mix well and squeeze out the excess water.2.Now, add maida along with some water and knead to form a smooth dough. Keep it aside for 5-10 minutes.3.Grease your hands with oil and divide the dough into equal portions. Take one of the dough balls and flatten it gently using your fingers.4.Heat a tawa set on a low-medium flame and place the flattened dough on it. Cook on each side until it becomes golden brown and crispy. You can even drizzle some ghee over it.5.Repeat the process with the remaining dough. Sri Lankan pol roti is ready! Serve hot and enjoy!",
        ingredients:["onion", "jeera", "salt", "oil", "water", "chillies"],
        description: "This is a vegetarian dish, which is very easy to make. Sri Lankan Pol Roti is made with coconut] green chilies and with mils spices.",
    },
    {
        name: "Sri Lankan Pol Roti Recipe",
        time: "25min",
        image: "https://c.ndtvimg.com/2023-08/v9qdbrf8_naan_625x300_08_August_23.jpg",
        method: "1.To make this roti, add grated coconut, green chillies, onion, curry leaves, and salt to a bowl. Mix well and squeeze out the excess water.2.Now, add maida along with some water and knead to form a smooth dough. Keep it aside for 5-10 minutes.3.Grease your hands with oil and divide the dough into equal portions. Take one of the dough balls and flatten it gently using your fingers.4.Heat a tawa set on a low-medium flame and place the flattened dough on it. Cook on each side until it becomes golden brown and crispy. You can even drizzle some ghee over it.5.Repeat the process with the remaining dough. Sri Lankan pol roti is ready! Serve hot and enjoy!",
        ingredients:["onion", "jeera", "salt", "oil", "water", "chillies"],
        description: "This is a vegetarian dish, which is very easy to make. Sri Lankan Pol Roti is made with coconut] green chilies and with mils spices.",
    },
    {
        name: "Onion Garlic Parantha Recipe",
        time: "15min",
        image: "https://c.ndtvimg.com/2021-05/7m893iug_parantha_625x300_05_May_21.jpg",
        method: "1.Heat oil in a pan. Add onion, garlic and cumin powder.2.Saute till the raw smell of garlic goes away and onions turn soft, not brown.3.Remove from gas, add green chilli, garam masala and coriander leaves.4.Use this mixture to fill your parathas and enjoy your meal.",
        ingredients:["onion", "flour", "salt", "oil", "garlic", "chillies", "coriander"],
        description: "Onion Garlic Parantha is a delectable flatbread recipe that can be enjoyed for any meal during the day. With the aromatic flavour of garlic and crispiness of onion, this recipe is very easy to make. Prepared with a handful of ingredients such as all purpose flour, garlic cloves, coriander leaves, and ghee. So, what are you waiting for? Make these onion garlic parathas and serve them piping hot with mint chutney and pickle.",
    },
    {
        name: "Kalakand",
        time: "25min",
        image: "https://c.ndtvimg.com/2023-11/r4n6brao_kalakand_625x300_07_November_23.jpg",
        method: "1.Add Cashews, Almonds, Pistachio and Paneer to the Jar2.Grind the ingredients : Blade speed 12 for 10 seconds & Blade speed 11 for 10 secondsAdd the Milk and Green Cardamom Powder3.Cook for 15 minutes at 95℃ with the blade speed set to Slow Stir. Add Condensed Milk- Mix in all the ingredients at Speed 1 for 5 seconds4.Cook the mixture together for 15 minutes at 95℃ with the blade speed set to Stir",
        ingredients:["paneer", "milk"],
        description: "Kalakand is a popular sweet that can be easily made on this festive season. All you need some cashew, almonds, paneer, milk and sugar.",
    },
    {
        name: "Gur Choorma Ladoo",
        time: "35min",
        image: "https://c.ndtvimg.com/2023-04/qocd5afg_atta-ladoo_625x300_05_April_23.jpg",
        method: "1.To make ladoo wheat flour, jaggery, nutmeg powder, oil and ghee are required. You have to first take flour, add ghee or oil and knead it into a stiff dough with the help of lukewarm water.2.After kneading the dough, you will have to rest it for 15 minutes.3.Make muthiyas of dough and heat oil in a pan. Deep fry all the prepared muthiyas until they become golden crispy.4.After frying, cool them, break them into pieces and then grind them in a mixer. Now take out this mixture in a vessel, melt jaggery in a pan, add it to this mixture and mix well.5.Add cardamom powder and a little ground nutmeg to it. Now heat ghee and make ladoo by mixing it in this mixture, coat these ladoos with poppy seeds.6.If you want, you can also include dry fruits in it. These ladoos can be prepared and stored for a month.",
        ingredients:["flour", "ghee", "oil"],
        description: "Gud Choorma Ladoo is a popular sweet made in Indian homes on many festivals and puja occasions. It tastes very tasty and is perfect to make this time on the occasion of Ganesh Chaturthi.",
    },
    {
        name: "Gulkand Ice Cream",
        time: "20min",
        image: "https://c.ndtvimg.com/2023-06/ie65asm8_ice-cream_625x300_19_June_23.jpg",
        method: "Mix all ingredients together and keep in refrigerator for 5-6 hours and when well set, scoop out and serve well garnished.",
        ingredients:["water", "sugar", "curd"],
        description: "This is a quick and easy cream recipe which is perfect to make in this summer season.",
    },
    {
        name: "Aloo Palak Paratha",
        time: "30min",
        image: "https://c.ndtvimg.com/2023-05/icruoj8o_paratha_650x400_21_May_23.jpg",
        method: "1.Mix all the ingredients of the dough and knead it well. Cover and keep aside for 15 minutes.2.In a kadhai, heat 1 tbsp ghee/oil and add the garlic. After it turns brown, add the chopped onion and saute for a minute.3.Add chilli powder and spinach (palak). Cover and let it cook for 2 minutes.4.Next, add chaat masala and mashed potatoes. Mix well for 3-4 minutes. Turn off the stove, add grated cheese (optional) and allow to cool.5.Take the rested dough and knead it again for 2-3 minutes. Break off small balls and flatten them.6.Add around 1 tablespoon of the potato-spinach filling in the centre of each paratha. Fold the edges over each other to form an envelope/ potli shape and seal them well. Flatten carefully to ensure the stuffing does not come out.7.Heat ghee on a tawa and roast the parathas on both sides until golden brown. Add extra ghee around the edges as needed.",
        ingredients:["salt", "ghee", "chillies", "garlic", "onlion", "flour", "water"],
        description: "Give your regular aloo paratha a flavorful and nutritious twist with this unique paratha. Filled with the goodness of potatoes, spinach, spices and a little cheese, this stuffed paratha might just become your new favourite. Enjoy it for a power-packed breakfast or a wholesome lunch",
    },
    {
        name: "Banana Kheer",
        time: "20min",
        image: "https://c.ndtvimg.com/2023-03/sj88bc08_kheer_625x300_21_March_23.jpg",
        method: "1.Boil the milk on low-medium flame until it thickens.2.Add kesar, cardamom powder and dry fruits to it. Simmer until the kesar leaves colour.3.Take mashed banana in a bowl and add the milk to it.4.Garnish with sliced banana and serve.",
        ingredients:["milk"],
        description: "This banana kheer is a delicious recipe, which is not fulfill your dessert cravings, you can also have it in your breakfast.",
    }
    // {
    //     name: "Beetroot Halwa Recipe",
    //     time: "40min",
    //     image: "https://c.ndtvimg.com/2023-11/rt2d5vdg_beetroot-halwa_625x300_10_November_23.jpg",
    //     method: "In a wide pan, heat 2 tsp of ghee.2.Add the skin peel to the pan and sauté for a few minutes.3.Pour in the milk and cook over low to medium flame for about 15 minutes until the vegetables are thoroughly cooked and soft.4.Once the vegetables are cooked, add sugar and mava to the pan.5.Continue cooking for an additional 5 minutes until the mixture achieves a thick consistency.6.In a separate pan, sauté the assorted nuts in ghee until they turn a golden colour.7.Add the remaining ghee, cardamom pods and seeds, as well as the sautéed nuts, to the main mixture.8.Mix all the ingredients th,oroughly.9.Serve and enjoy the dish while it is warm.",
    //     // ingredient: "300 gms Carrot Skin Peel, 300 Beetroot Skin Peel, 125 Mava, 125 Sugar, 25 Desi Ghee, 15 Cashewnuts, 1 Cardamom Powder",
    //     description: "This beetroot halwa is a winter delight. If you want, you can easily make this Indian dessert at home this Diwali"
    // }
]